name: Continuous Integration

on: push
  
jobs:
  build:
    name: Build and publish package
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04

    permissions:
      packages: write
      contents: write

    env:
      BUILD_CONFIG: Release
      SOLUTION: TELFrontendRazor.sln
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OWNER: ${{ github.repository_owner }}
      AZURE_OWNER: ${{ secrets.TEL_AZURE_DEVOPS_USERNAME }}
      AZURE_PATH: ${{ secrets.AZURE_PACKAGES_PATH }}
      AZURE_KEY: ${{ secrets.AZURE_DEVOPS_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.2
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.2

      - name: Display GitVersion outputs
        run: |
          echo "Version will be set to: ${{ steps.gitversion.outputs.majorMinorPatch }}"

      - name: Add Azure artifact
        run: dotnet nuget add source "$AZURE_PATH" --name 'LearningHubFeed'  --username "$AZURE_OWNER" --password "$AZURE_KEY" --store-password-in-clear-text

      - name: Add github registry
        run: dotnet nuget add source --username "${{ github.actor }}" --password "$GITHUB_TOKEN" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$GITHUB_OWNER/index.json"

      - name: Dotnet build
        run:  dotnet build "$SOLUTION" --configuration release

      - name: Package nuget
        run: dotnet pack "$SOLUTION" --configuration "$BUILD_CONFIG" -o package /p:PackageVersion=${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./package/*.nupkg --api-key "$GITHUB_TOKEN" --source "github" --skip-duplicate

      - name: Push generated package to Azure Feed
        run: dotnet nuget push ./package/*.nupkg  --source "$AZURE_PATH"   --api-key "$AZURE_KEY"  --skip-duplicate

      - name: Tag published version
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.gitversion.outputs.majorMinorPatch }}',
              sha: context.sha
            })